server:
  port: 8001
  max-http-header-size: 10000000
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: javaApi
  http:
    encoding:
      charset: utf-8
      force: true
  redis:
    host: redis-service.default
    password: Wang628625
    port: 6379
    timeout: 3000
    pool:
      max-idle: 500
      min-idle: 50
      max-active: 100
      max-wait : 100
  data:
    mongodb:
      custom:
        hosts:
          - mongodb-service.default
        ports:
          - 7801
        username: funcoin
        password: Funcoin123!!!
        database: funcoin
        connections-per-host: 200
        min-connections-per-host: 200
logging:
  config: classpath:conf/log4j2-d.xml
mybatis:
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: net.cyweb.model
mapper:
  before: true
  mappers: net.cyweb.config.mybatis.TkMapper
  uuid: select replace(uuid(),'-','')
  identity: MYSQL
  not-empty: false
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
druid:
  url: jdbc:mysql://mysql-service.default:3306/funcoin_new?useUnicode=true&&characterEncoding=utf-8
  driver: com.mysql.jdbc.Driver
  username: funcoin_new
  password: 'funcoinnew!!!lisimeng'
  initial-size: 5
  max-active: 20
  test-on-borrow: true
eureka:
  instance:
    preferIpAddress: true
    ip-address: 10.97.70.229
    port: 8001
  client:
    serviceUrl:
      defaultZone: http://funcoin-eureka-service:8001/eureka/
feign:
  hystrix:
    enabled: false
myProps:
  ftp:
    rootPath: /upload/
    savePath: id_card/
    newReadHost: http://192.168.32.41:30010/
    newReadHost2: http://222.185.192.230:30010/
    oldReadHost: http://static.bimin.vip/
    adminNewPath: admin_new/images/