server:
  port: 8080
  tomcat:
      uri-encoding: UTF-8
spring:
  application:
    name: spring-cloud-web
  http:
      encoding:
        charset: utf-8
        force: true
logging:
  config: classpath:conf/log4j2.xml
eureka:
  instance:
    hostname: 127.0.0.1
    port: 8001
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
feign:
  hystrix:
    enabled: true
management:
  health:
    mail:
      enabled: false
hystrix:
  dashboard:
    enable-ignore-connection-close-header: true