server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: ssh://git@code.cyweb.net:2222/root/cloud.git/     # 配置git仓库的地址
          search-paths: config-repo                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: wuhongbing                                             # git仓库的账号
          password: wuhongbing                                             # git仓库的密码

logging:
  config: classpath:conf/log4j2.xml